""""
same namespace as pxd.
""""
cdef class State:
    def __cinit__(...):
        # ...
    def __dealloc__(...):
        # ...
    cpdef real_t momentum(self):
        # ...
def setup(input_fname):
    # ...
cpdef run(State st):
    # ...calls step function repeatedly...
cpdef int step(State st, real_t timestep):
    # ...advance st one time step...
def output(State st):
    # ...